apiVersion: v1
kind: PersistentVolume
metadata:
  name: odysseus-data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /volumes/ssd/k3s/odysseus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odysseus-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: odysseus-data-pv
