apiVersion: v1
kind: PersistentVolume
metadata:
  name: chromadb-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /volumes/ssd/k3s/chromadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: chromadb-data-pv
