apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
data:
  settings.yml: |
    use_default_settings: true

    server:
      secret_key: "__SEARXNG_SECRET__"
      limiter: false
      image_proxy: true

    search:
      safe_search: 0
      autocomplete: ""
      default_lang: "pt-BR"
      formats:
        - html
        - json

    ui:
      static_use_hash: true
      query_in_title: true
      default_locale: "pt-BR"

    enabled_plugins:
      - "Hash plugin"
      - "Search on category select"
      - "Tracker URL remover"

    outgoing:
      request_timeout: 3.0
      max_request_timeout: 15.0
