apiVersion: v1
kind: Secret
metadata:
  name: ai-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:davidcardoso-homelab/ai.git
  type: git
  name: ai-repository
  project: ai
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    COLOQUE_A_CHAVE_SSH_AQUI
    -----END OPENSSH PRIVATE KEY-----
